#!/usr/bin/env bash
# Script that pings an IP address 5 times to check if it's reachable

# Vérifie si un argument est passé
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping l'adresse IP 5 fois
ping -c 5 "$1"
