#!/usr/bin/env bash
# This script changes localhost to resolve to 127.0.0.2 and facebook.com to resolve to 8.8.8.8

# Exit on error
set -e

# Sauvegarde du fichier /etc/hosts si ce n'est pas déjà fait
[ ! -f /etc/hosts.bak ] && sudo cp /etc/hosts /etc/hosts.bak

# Supprimer les anciennes lignes correspondantes
sudo sed -i '/[[:space:]]localhost$/d' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

# Ajouter les nouvelles correspondances IP
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
